// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xgca.entity;

namespace xgca.entity.Migrations
{
    [DbContext(typeof(XGCAContext))]
    partial class XGCAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("xgca.entity.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("AddressTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("AddressId");

                    b.HasIndex("AddressTypeId");

                    b.ToTable("Address","General");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AddressLine = "None",
                            AddressTypeId = 1,
                            CityId = 1,
                            CityName = "None",
                            CountryId = 1,
                            CountryName = "Global",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2020, 10, 8, 9, 55, 31, 506, DateTimeKind.Utc).AddTicks(5719),
                            FullAddress = "None",
                            Guid = new Guid("21716a6c-4dee-422b-b2d9-74bf4b12e242"),
                            IsDeleted = (byte)1,
                            Latitude = "None",
                            Longitude = "None",
                            ModifiedBy = 0,
                            ModifiedOn = new DateTime(2020, 10, 8, 9, 55, 31, 507, DateTimeKind.Utc).AddTicks(350),
                            StateId = 1,
                            StateName = "None",
                            ZipCode = "None"
                        });
                });

            modelBuilder.Entity("xgca.entity.Models.AddressType", b =>
                {
                    b.Property<int>("AddressTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("AddressTypeId");

                    b.ToTable("AddressType","Settings");

                    b.HasData(
                        new
                        {
                            AddressTypeId = 1,
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2020, 10, 8, 9, 55, 31, 496, DateTimeKind.Utc).AddTicks(9910),
                            Guid = new Guid("1e0621b2-b7ea-4d48-8be2-f09980694816"),
                            IsDeleted = (byte)0,
                            ModifiedBy = 0,
                            ModifiedOn = new DateTime(2020, 10, 8, 9, 55, 31, 497, DateTimeKind.Utc).AddTicks(3533),
                            Name = "Company"
                        },
                        new
                        {
                            AddressTypeId = 2,
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2020, 10, 8, 9, 55, 31, 504, DateTimeKind.Utc).AddTicks(1232),
                            Guid = new Guid("95ec682b-074f-42bb-9fed-d4dbde41e41d"),
                            IsDeleted = (byte)0,
                            ModifiedBy = 0,
                            ModifiedOn = new DateTime(2020, 10, 8, 9, 55, 31, 504, DateTimeKind.Utc).AddTicks(1341),
                            Name = "Residential"
                        });
                });

            modelBuilder.Entity("xgca.entity.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditLogAction")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KeyFieldId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLog","Settings");
                });

            modelBuilder.Entity("xgca.entity.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccreditedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("CUCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(160)")
                        .HasMaxLength(160);

                    b.Property<int>("ContactDetailId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(74)")
                        .HasMaxLength(74);

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TaxExemption")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TaxExemptionStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("WebsiteURL")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("CompanyId");

                    b.HasIndex("AddressId");

                    b.HasIndex("ContactDetailId");

                    b.ToTable("Company","Company");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            AddressId = 1,
                            ClientId = 1,
                            CompanyName = "None",
                            ContactDetailId = 1,
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2020, 10, 8, 9, 55, 31, 514, DateTimeKind.Utc).AddTicks(4411),
                            EmailAddress = "None",
                            Guid = new Guid("3608a083-fbe5-44d5-afef-c7814100aec7"),
                            ImageURL = "None",
                            IsDeleted = (byte)1,
                            ModifiedBy = 0,
                            ModifiedOn = new DateTime(2020, 10, 8, 9, 55, 31, 514, DateTimeKind.Utc).AddTicks(9023),
                            Status = (byte)0,
                            TaxExemption = (byte)0,
                            TaxExemptionStatus = (byte)0,
                            WebsiteURL = "None"
                        });
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyGroupResource", b =>
                {
                    b.Property<int>("CompanyGroupResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyServiceRoleId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("GroupResourceId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("e2a63825-ceda-4a87-b643-f2e211150318"));

                    b.Property<byte>("IsAllowed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("ModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("CompanyGroupResourceId");

                    b.HasIndex("CompanyServiceRoleId");

                    b.ToTable("CompanyGroupResource","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyService", b =>
                {
                    b.Property<int>("CompanyServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CompanyServiceId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyService","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyServiceRole", b =>
                {
                    b.Property<int>("CompanyServiceRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyServiceId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyServiceRoleId");

                    b.HasIndex("CompanyServiceId");

                    b.ToTable("CompanyServiceRole","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyServiceUser", b =>
                {
                    b.Property<int>("CompanyServiceUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyServiceId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyServiceRoleId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyUserId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsLocked")
                        .HasColumnType("tinyint");

                    b.Property<int>("IsMasterUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyServiceUserId");

                    b.HasIndex("CompanyServiceId");

                    b.HasIndex("CompanyServiceRoleId");

                    b.HasIndex("CompanyUserId");

                    b.ToTable("CompanyServiceUser","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyServiceUserRole", b =>
                {
                    b.Property<int>("CompanyServiceUserRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyServiceRoleId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyServiceUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyServiceUserRoleID");

                    b.HasIndex("CompanyServiceId");

                    b.HasIndex("CompanyServiceRoleId");

                    b.HasIndex("CompanyServiceUserId");

                    b.ToTable("CompanyServiceUserRole","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyUser", b =>
                {
                    b.Property<int>("CompanyUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("CompanyUserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CompanyUser","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.ContactDetail", b =>
                {
                    b.Property<int>("ContactDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("FaxPrefix")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("FaxPrefixId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MobilePrefix")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("MobilePrefixId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PhonePrefix")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("PhonePrefixId")
                        .HasColumnType("int");

                    b.HasKey("ContactDetailId");

                    b.ToTable("ContactDetail","General");

                    b.HasData(
                        new
                        {
                            ContactDetailId = 1,
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2020, 10, 8, 9, 55, 31, 510, DateTimeKind.Utc).AddTicks(4294),
                            Fax = "None",
                            FaxPrefix = "None",
                            FaxPrefixId = 1,
                            Guid = new Guid("1f5cb3b9-992b-4279-acf7-7f0273abbf03"),
                            IsDeleted = (byte)1,
                            Mobile = "None",
                            MobilePrefix = "None",
                            MobilePrefixId = 1,
                            ModifiedBy = 0,
                            ModifiedOn = new DateTime(2020, 10, 8, 9, 55, 31, 510, DateTimeKind.Utc).AddTicks(8924),
                            Phone = "None",
                            PhonePrefix = "None",
                            PhonePrefixId = 1
                        });
                });

            modelBuilder.Entity("xgca.entity.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumberPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNumberPrefixId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestType")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumberPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumberPrefixId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberPrefixId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuestId");

                    b.ToTable("Guest","Company");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            AddressLine = "None",
                            CityId = "None",
                            CityName = "None",
                            CompanyId = 1,
                            CountryId = 1,
                            CountryName = "Global",
                            CreatedBy = 0,
                            CreatedOn = new DateTime(2020, 10, 8, 9, 55, 31, 520, DateTimeKind.Utc).AddTicks(3012),
                            DeletedBy = 0,
                            DeletedOn = new DateTime(2020, 10, 8, 9, 55, 31, 521, DateTimeKind.Utc).AddTicks(3195),
                            EmailAddress = "None",
                            FaxNumber = "None",
                            FaxNumberPrefix = "None",
                            FaxNumberPrefixId = "None",
                            FirstName = "None",
                            GuestName = "None",
                            GuestType = 0,
                            Id = new Guid("7bbe1f11-e04a-4a8b-afe1-ec55eba13d66"),
                            IsDeleted = (byte)1,
                            IsGuest = false,
                            LastName = "None",
                            MobileNumber = "None",
                            MobileNumberPrefix = "None",
                            MobileNumberPrefixId = "None",
                            ModifiedBy = 0,
                            ModifiedOn = new DateTime(2020, 10, 8, 9, 55, 31, 520, DateTimeKind.Utc).AddTicks(7058),
                            PhoneNumber = "None",
                            PhoneNumberPrefix = "None",
                            PhoneNumberPrefixId = "None",
                            StateId = "None",
                            StateName = "None",
                            ZipCode = "None"
                        });
                });

            modelBuilder.Entity("xgca.entity.Models.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InviteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InviteType")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InviteId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Invite","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.PreferredContact", b =>
                {
                    b.Property<int>("PreferredContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("PreferredContactId");

                    b.ToTable("PreferredContact","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.PreferredProvider", b =>
                {
                    b.Property<int>("PreferredProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreferredProviderId");

                    b.ToTable("PreferredProvider","Company");
                });

            modelBuilder.Entity("xgca.entity.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactDetailId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IsLocked")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("UserId");

                    b.HasIndex("ContactDetailId");

                    b.ToTable("User","Users");
                });

            modelBuilder.Entity("xgca.entity.Models.Address", b =>
                {
                    b.HasOne("xgca.entity.Models.AddressType", "AddressTypes")
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.Company", b =>
                {
                    b.HasOne("xgca.entity.Models.Address", "Addresses")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xgca.entity.Models.ContactDetail", "ContactDetails")
                        .WithMany()
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyGroupResource", b =>
                {
                    b.HasOne("xgca.entity.Models.CompanyServiceRole", "CompanyServiceRole")
                        .WithMany("CompanyGroupResources")
                        .HasForeignKey("CompanyServiceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyService", b =>
                {
                    b.HasOne("xgca.entity.Models.Company", "Companies")
                        .WithMany("CompanyServices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyServiceRole", b =>
                {
                    b.HasOne("xgca.entity.Models.CompanyService", "CompanyServices")
                        .WithMany("CompanyServiceRoles")
                        .HasForeignKey("CompanyServiceId");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyServiceUser", b =>
                {
                    b.HasOne("xgca.entity.Models.CompanyService", "CompanyServices")
                        .WithMany("CompanyServiceUsers")
                        .HasForeignKey("CompanyServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xgca.entity.Models.CompanyServiceRole", "CompanyServiceRoles")
                        .WithMany("CompanyServiceUsers")
                        .HasForeignKey("CompanyServiceRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xgca.entity.Models.CompanyUser", "CompanyUsers")
                        .WithMany("CompanyServiceUsers")
                        .HasForeignKey("CompanyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyServiceUserRole", b =>
                {
                    b.HasOne("xgca.entity.Models.CompanyService", "CompanyService")
                        .WithMany("CompanyServiceUserRoles")
                        .HasForeignKey("CompanyServiceId");

                    b.HasOne("xgca.entity.Models.CompanyServiceRole", "CompanyServiceRole")
                        .WithMany("CompanyServiceUserRoles")
                        .HasForeignKey("CompanyServiceRoleId");

                    b.HasOne("xgca.entity.Models.CompanyServiceUser", "CompanyServiceUser")
                        .WithMany("CompanyServiceUserRoles")
                        .HasForeignKey("CompanyServiceUserId");
                });

            modelBuilder.Entity("xgca.entity.Models.CompanyUser", b =>
                {
                    b.HasOne("xgca.entity.Models.Company", "Companies")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("xgca.entity.Models.User", "Users")
                        .WithOne("CompanyUsers")
                        .HasForeignKey("xgca.entity.Models.CompanyUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.Invite", b =>
                {
                    b.HasOne("xgca.entity.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("xgca.entity.Models.User", b =>
                {
                    b.HasOne("xgca.entity.Models.ContactDetail", "ContactDetails")
                        .WithMany()
                        .HasForeignKey("ContactDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
